FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY analytics/analytics.csproj analytics/
COPY organaizer/organaizer.csproj organaizer/
RUN dotnet restore analytics/analytics.csproj
COPY analytics analytics
COPY organaizer organaizer
RUN dotnet publish analytics/analytics.csproj -c Release -o /app/publish --no-restore
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/publish .
ENV ASPNETCORE_URLS=http://+:8080
ENTRYPOINT ["dotnet","analytics.dll"]
