using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using organaizer.Application;
using organaizer.Domain;
using organaizer.Infrastructure;
namespace organaizer.Pages.Operations;
public sealed class CreateModel(Dispatcher dispatcher, FinanceDbContext db, ActiveCompany active) : PageModel
{
 [BindProperty] public InputModel Input {get;set;}=new(); public bool IsCopy{get;private set;}public List<SelectListItem> Companies{get;private set;}=[];public List<SelectListItem>Counterparties{get;private set;}=[];public List<SelectListItem>Currencies{get;private set;}=[];public List<MoneyAccount>AccountItems{get;private set;}=[];public Dictionary<Guid,decimal>AccountBalances{get;private set;}=[];public IReadOnlyDictionary<string,string>Types=>OperationTypes.All;
 public sealed class InputModel{[Required]public Guid CompanyId{get;set;}public Guid?CounterpartyId{get;set;}[Required]public string TypeCode{get;set;}="BUY_USDT_USD";public DateTime OccurredAt{get;set;}=DateTime.Today;public DateTime?DueAt{get;set;}[Required]public string SellCurrency{get;set;}="USD";[Range(typeof(decimal),"0.00000001","9999999999999999")]public decimal SellAmount{get;set;}[Required]public string BuyCurrency{get;set;}="USDT";[Range(typeof(decimal),"0.00000001","9999999999999999")]public decimal BuyAmount{get;set;}public decimal?ExchangeRate{get;set;}public decimal FeeAmount{get;set;}public string FeeCurrency{get;set;}="USD";public decimal BaseCurrencyProfit{get;set;}public Guid?SellAccountId{get;set;}public Guid?BuyAccountId{get;set;}public string?Note{get;set;}}
 public async Task<IActionResult> OnGetAsync(Guid? copyFrom)
 {
  if(!copyFrom.HasValue){await Load();return Page();}
  var source=await db.Operations.AsNoTracking().Include(x=>x.Settlements).SingleOrDefaultAsync(x=>x.Id==copyFrom&&x.CompanyId==active.RequiredId);
  if(source is null)return NotFound();
  var sellSettlement=source.Settlements.Where(x=>x.Amount<0).OrderBy(x=>x.OccurredAt).FirstOrDefault();var buySettlement=source.Settlements.Where(x=>x.Amount>0).OrderBy(x=>x.OccurredAt).FirstOrDefault();
  Input=new InputModel{CompanyId=active.RequiredId,CounterpartyId=source.CounterpartyId,TypeCode=source.TypeCode,OccurredAt=source.OccurredAt.Date,DueAt=source.DueAt?.Date,SellCurrency=source.SellCurrency,SellAmount=source.SellAmount,BuyCurrency=source.BuyCurrency,BuyAmount=source.BuyAmount,ExchangeRate=source.ExchangeRate,FeeAmount=source.FeeAmount,FeeCurrency=source.FeeCurrency,BaseCurrencyProfit=source.BaseCurrencyProfit,SellAccountId=sellSettlement?.AccountId,BuyAccountId=buySettlement?.AccountId,Note=source.Note};
  await Load();
  if(!Input.SellAccountId.HasValue)Input.SellAccountId=FindImportedAccount(source.SourceAccount,source.SellCurrency);
  if(!Input.BuyAccountId.HasValue)Input.BuyAccountId=FindImportedAccount(source.DestinationAccount,source.BuyCurrency);
  IsCopy=true;return Page();
 }
 public async Task<JsonResult>OnGetRateAsync(string sellCurrency,string buyCurrency,DateTime date){async Task<decimal?>Rate(string currency){if(currency is "USD" or "USDT")return 1m;var end=new DateTimeOffset(date.Date.AddDays(1),TimeSpan.Zero);return await db.ExchangeRates.AsNoTracking().Where(x=>x.Currency==currency&&x.EffectiveAt<end).OrderByDescending(x=>x.EffectiveAt).ThenByDescending(x=>x.SourceOrder).Select(x=>(decimal?)x.RateToUsd).FirstOrDefaultAsync();}var sell=await Rate(sellCurrency.ToUpperInvariant());var buy=await Rate(buyCurrency.ToUpperInvariant());return new JsonResult(new{found=sell.HasValue&&buy.HasValue,rate=sell.HasValue&&buy.HasValue&&buy!=0?sell/buy:null});}
 public async Task<IActionResult>OnPostAsync(){Input.CompanyId=active.RequiredId;ModelState.Remove("Input.CompanyId");if(Input.CounterpartyId.HasValue&&!await db.Counterparties.AnyAsync(x=>x.Id==Input.CounterpartyId&&x.CompanyId==active.RequiredId))ModelState.AddModelError("Input.CounterpartyId","Клиент не принадлежит компании");var ids=new[]{Input.SellAccountId,Input.BuyAccountId}.Where(x=>x.HasValue).Select(x=>x!.Value).ToList();var selected=await db.Accounts.Include(x=>x.FinancialInstitution).Where(x=>x.CompanyId==active.RequiredId&&ids.Contains(x.Id)).ToListAsync();var sell=Input.SellAccountId.HasValue?selected.SingleOrDefault(x=>x.Id==Input.SellAccountId):null;var buy=Input.BuyAccountId.HasValue?selected.SingleOrDefault(x=>x.Id==Input.BuyAccountId):null;if(Input.SellAccountId.HasValue&&(sell is null||sell.Currency!=Input.SellCurrency))ModelState.AddModelError("Input.SellAccountId","Счет списания должен быть в валюте операции");if(Input.BuyAccountId.HasValue&&(buy is null||buy.Currency!=Input.BuyCurrency))ModelState.AddModelError("Input.BuyAccountId","Счет зачисления должен быть в валюте операции");if(!ModelState.IsValid){await Load();return Page();}var i=Input;await using var tx=await db.Database.BeginTransactionAsync();var operationId=await dispatcher.Send(new CreateOperationCommand(active.RequiredId,i.CounterpartyId,i.TypeCode,new DateTimeOffset(i.OccurredAt,TimeSpan.Zero),i.DueAt.HasValue?new DateTimeOffset(i.DueAt.Value,TimeSpan.Zero):null,i.SellCurrency,i.SellAmount,i.BuyCurrency,i.BuyAmount,i.FeeAmount,i.FeeCurrency,i.BaseCurrencyProfit,i.ExchangeRate,sell?.Name,buy?.Name,i.Note));if(sell is not null)await dispatcher.Send(new AddSettlementCommand(operationId,sell.Id,new DateTimeOffset(i.OccurredAt,TimeSpan.Zero),-i.SellAmount,i.SellCurrency,"Списание по операции"));if(buy is not null)await dispatcher.Send(new AddSettlementCommand(operationId,buy.Id,new DateTimeOffset(i.OccurredAt,TimeSpan.Zero),i.BuyAmount,i.BuyCurrency,"Зачисление по операции"));await tx.CommitAsync();return RedirectToPage("Index");}
 async Task Load(){Input.CompanyId=active.RequiredId;Companies=await db.Companies.AsNoTracking().Where(x=>x.Id==active.RequiredId).Select(x=>new SelectListItem(x.Name,x.Id.ToString())).ToListAsync();Counterparties=await db.Counterparties.AsNoTracking().Where(x=>x.IsActive&&x.CompanyId==active.RequiredId).OrderBy(x=>x.Name).Select(x=>new SelectListItem(x.Name,x.Id.ToString())).ToListAsync();Currencies=await db.Currencies.AsNoTracking().Where(x=>x.IsActive).OrderBy(x=>x.Code).Select(x=>new SelectListItem(x.Code+" — "+x.Name,x.Code)).ToListAsync();AccountItems=await db.Accounts.AsNoTracking().Include(x=>x.FinancialInstitution).Where(x=>x.IsActive&&x.CompanyId==active.RequiredId&&x.FinancialInstitutionId!=null).OrderBy(x=>x.Name).ToListAsync();foreach(var account in AccountItems)AccountBalances[account.Id]=await BalanceCalculator.GetAsync(db,account.Id);}
 Guid? FindImportedAccount(string? name,string currency)=>AccountItems.FirstOrDefault(x=>x.Currency==currency&&(string.Equals(x.Name,name,StringComparison.OrdinalIgnoreCase)||string.Equals(x.FinancialInstitution?.Name,name,StringComparison.OrdinalIgnoreCase)))?.Id;
}
