using System.ComponentModel.DataAnnotations; using Microsoft.AspNetCore.Mvc; using Microsoft.AspNetCore.Mvc.RazorPages; using Microsoft.AspNetCore.Mvc.Rendering; using Microsoft.EntityFrameworkCore; using organaizer.Application; using organaizer.Domain; using organaizer.Infrastructure;
namespace organaizer.Pages.Operations;
public sealed class EditModel(Dispatcher dispatcher,FinanceDbContext db,ActiveCompany active):PageModel
{
 [BindProperty]public InputModel Input{get;set;}=new();public List<SelectListItem> Companies{get;private set;}=[];public List<SelectListItem> Counterparties{get;private set;}=[];public List<SelectListItem>Currencies{get;private set;}=[];public List<SelectListItem>Institutions{get;private set;}=[];public IReadOnlyDictionary<string,string> Types=>OperationTypes.All;public IEnumerable<OperationStatus> Statuses=>Enum.GetValues<OperationStatus>();
 public sealed class InputModel{public Guid Id{get;set;}[Required]public Guid CompanyId{get;set;}public Guid?CounterpartyId{get;set;}[Required]public string TypeCode{get;set;}="";public DateTime OccurredAt{get;set;}public DateTime?DueAt{get;set;}[Required]public string SellCurrency{get;set;}="";[Range(typeof(decimal),"0.00000001","9999999999999999")]public decimal SellAmount{get;set;}[Required]public string BuyCurrency{get;set;}="";[Range(typeof(decimal),"0.00000001","9999999999999999")]public decimal BuyAmount{get;set;}public decimal FeeAmount{get;set;}[Required]public string FeeCurrency{get;set;}="";public decimal BaseCurrencyProfit{get;set;}public OperationStatus Status{get;set;}public string?SourceAccount{get;set;}public string?DestinationAccount{get;set;}public string?Note{get;set;}}
 public async Task<IActionResult>OnGetAsync(Guid id){var x=await db.Operations.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id);if(x is null)return NotFound();Input=new(){Id=x.Id,CompanyId=x.CompanyId,CounterpartyId=x.CounterpartyId,TypeCode=x.TypeCode,OccurredAt=x.OccurredAt.DateTime,DueAt=x.DueAt?.DateTime,SellCurrency=x.SellCurrency,SellAmount=x.SellAmount,BuyCurrency=x.BuyCurrency,BuyAmount=x.BuyAmount,FeeAmount=x.FeeAmount,FeeCurrency=x.FeeCurrency,BaseCurrencyProfit=x.BaseCurrencyProfit,Status=x.Status,SourceAccount=x.SourceAccount,DestinationAccount=x.DestinationAccount,Note=x.Note};await Load();return Page();}
 public async Task<IActionResult>OnPostAsync(){Input.CompanyId=active.RequiredId;ModelState.Remove("Input.CompanyId");if(!ModelState.IsValid){await Load();return Page();}var current=await db.Operations.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==Input.Id);if(current is null)return NotFound();var i=Input;await dispatcher.Send(new UpdateOperationCommand(i.Id,active.RequiredId,i.CounterpartyId,i.TypeCode,new DateTimeOffset(i.OccurredAt,TimeSpan.Zero),i.DueAt.HasValue?new DateTimeOffset(i.DueAt.Value,TimeSpan.Zero):null,i.SellCurrency,i.SellAmount,i.BuyCurrency,i.BuyAmount,i.FeeAmount,i.FeeCurrency,i.BaseCurrencyProfit,current.Status,i.SourceAccount,i.DestinationAccount,i.Note));return RedirectToPage("Details",new{id=i.Id});}
 async Task Load(){Companies=await db.Companies.AsNoTracking().Where(x=>x.Id==active.RequiredId).Select(x=>new SelectListItem(x.Name,x.Id.ToString())).ToListAsync();Counterparties=await db.Counterparties.AsNoTracking().Where(x=>x.IsActive&&x.CompanyId==active.RequiredId).OrderBy(x=>x.Name).Select(x=>new SelectListItem(x.Name,x.Id.ToString())).ToListAsync();Currencies=await db.Currencies.AsNoTracking().Where(x=>x.IsActive).OrderBy(x=>x.Code).Select(x=>new SelectListItem(x.Code+" — "+x.Name,x.Code)).ToListAsync();Institutions=await db.FinancialInstitutions.AsNoTracking().Where(x=>x.IsActive).OrderBy(x=>x.Name).Select(x=>new SelectListItem(x.Name+" · "+x.Kind,x.Name)).ToListAsync();}
}
