using Microsoft.AspNetCore.Mvc; using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using organaizer.Application;
using organaizer.Domain;
using organaizer.Infrastructure;
namespace organaizer.Pages.Operations;
public sealed class IndexModel(FinanceDbContext db,Dispatcher dispatcher,ActiveCompany active):PageModel
{
 public const int PageSize=20;public List<TradeOperation> Items {get;private set;}=[];public List<Domain.Company>Companies{get;private set;}=[];
 public string?Search{get;private set;}public Guid?CompanyId{get;private set;}public string?TypeCode{get;private set;}public string?Status{get;private set;}public DateTime?From{get;private set;}public DateTime?To{get;private set;}public int PageNumber{get;private set;}=1;public int TotalPages{get;private set;}public int TotalCount{get;private set;}
 public async Task OnGetAsync(string?search,Guid?companyId,string?typeCode,string?status,DateTime?from,DateTime?to,int pageNumber=1){Search=search?.Trim();CompanyId=active.RequiredId;TypeCode=typeCode;Status=status;From=from;To=to;PageNumber=Math.Max(1,pageNumber);Companies=await db.Companies.AsNoTracking().Where(x=>x.Id==active.RequiredId).ToListAsync();var q=db.Operations.AsNoTracking().Include(x=>x.Counterparty).Where(x=>x.CompanyId==active.RequiredId);if(!string.IsNullOrWhiteSpace(Search)){var term=Search.ToLower();q=q.Where(x=>(x.Counterparty!=null&&x.Counterparty.Name.ToLower().Contains(term))||(x.Note!=null&&x.Note.ToLower().Contains(term))||x.SellCurrency.ToLower().Contains(term)||x.BuyCurrency.ToLower().Contains(term));}if(!string.IsNullOrWhiteSpace(typeCode))q=q.Where(x=>x.TypeCode==typeCode);q=status switch{OperationStatuses.Completed=>q.Where(x=>x.Status==OperationStatus.Settled),OperationStatuses.Cancelled=>q.Where(x=>x.Status==OperationStatus.Cancelled),OperationStatuses.Created=>q.Where(x=>x.Status!=OperationStatus.Settled&&x.Status!=OperationStatus.Cancelled),_=>q};if(from.HasValue){var start=new DateTimeOffset(DateTime.SpecifyKind(from.Value.Date,DateTimeKind.Utc));q=q.Where(x=>x.OccurredAt>=start);}if(to.HasValue){var end=new DateTimeOffset(DateTime.SpecifyKind(to.Value.Date.AddDays(1),DateTimeKind.Utc));q=q.Where(x=>x.OccurredAt<end);}TotalCount=await q.CountAsync();TotalPages=Math.Max(1,(int)Math.Ceiling(TotalCount/(double)PageSize));PageNumber=Math.Min(PageNumber,TotalPages);Items=await q.OrderByDescending(x=>x.OccurredAt).ThenByDescending(x=>x.Id).Skip((PageNumber-1)*PageSize).Take(PageSize).ToListAsync();}
 public async Task<IActionResult> OnPostCompleteAsync(Guid id,string?search,string?typeCode,string?status,DateTime?from,DateTime?to,int pageNumber=1){await dispatcher.Send(new CompleteOperationCommand(id));TempData["Message"]="Операция завершена";return RedirectToPage(new{search,typeCode,status,from=from?.ToString("yyyy-MM-dd"),to=to?.ToString("yyyy-MM-dd"),pageNumber});}
 public async Task<IActionResult> OnPostCancelAsync(Guid id,string?search,Guid?companyId,string?typeCode,string?status,DateTime?from,DateTime?to,int pageNumber=1){await dispatcher.Send(new CancelOperationCommand(id));TempData["Message"]="Операция отменена";return RedirectToPage(new{search,companyId,typeCode,status,from=from?.ToString("yyyy-MM-dd"),to=to?.ToString("yyyy-MM-dd"),pageNumber});}
}
