using Microsoft.AspNetCore.Mvc;using Microsoft.AspNetCore.Mvc.Rendering;using Microsoft.AspNetCore.Mvc.RazorPages;using Microsoft.EntityFrameworkCore;using organaizer.Infrastructure;
namespace organaizer.Pages.Expenses;
public sealed class EditModel(FinanceDbContext db):PageModel
{
 [BindProperty]public ExpenseForm Input{get;set;}=new();public SelectList Companies{get;private set;}=null!;public SelectList Accounts{get;private set;}=null!;public SelectList Currencies{get;private set;}=null!;
 public async Task<IActionResult>OnGetAsync(Guid id){var x=await db.Expenses.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id);if(x is null)return NotFound();Input=new(){Id=x.Id,CompanyId=x.CompanyId,AccountId=x.AccountId,OccurredAt=x.OccurredAt.DateTime,Category=x.Category,Amount=x.Amount,Currency=x.Currency,Note=x.Note};await Load();return Page();}
 public async Task<IActionResult>OnPostAsync(){var x=await db.Expenses.SingleOrDefaultAsync(x=>x.Id==Input.Id);if(x is null)return NotFound();var account=await db.Accounts.AsNoTracking().SingleOrDefaultAsync(a=>a.Id==Input.AccountId);if(account is null||account.CompanyId!=Input.CompanyId)ModelState.AddModelError("Input.AccountId","Счет не принадлежит выбранной компании");if(!ModelState.IsValid){await Load();return Page();}x.CompanyId=Input.CompanyId;x.AccountId=Input.AccountId;x.OccurredAt=new DateTimeOffset(Input.OccurredAt,TimeSpan.Zero);x.Category=Input.Category.Trim();x.Amount=Input.Amount;x.Currency=Input.Currency.ToUpperInvariant();x.BaseCurrencyAmount=0;x.Note=Input.Note?.Trim();await db.SaveChangesAsync();return RedirectToPage("Index");}
 public async Task<IActionResult>OnPostDeleteAsync(){var x=await db.Expenses.SingleOrDefaultAsync(x=>x.Id==Input.Id);if(x is not null){db.Expenses.Remove(x);await db.SaveChangesAsync();}return RedirectToPage("Index");}
 async Task Load(){Companies=new SelectList(await db.Companies.AsNoTracking().OrderBy(x=>x.Name).ToListAsync(),"Id","Name",Input.CompanyId);Accounts=new SelectList(await db.Accounts.AsNoTracking().OrderBy(x=>x.Name).ToListAsync(),"Id","Name",Input.AccountId);Currencies=new SelectList(await db.Currencies.AsNoTracking().Where(x=>x.IsActive).OrderBy(x=>x.Code).ToListAsync(),"Code","Code",Input.Currency);ViewData["Companies"]=Companies;ViewData["Accounts"]=Accounts;ViewData["Currencies"]=Currencies;}
}
